### find the tens digit from a number of an array


In [112]:
import pandas as pd
import numpy as np

In [113]:
numbers = np.random.randint(0,100,10)
numbers

array([80, 46, 62, 58, 64, 77, 98, 20, 35, 37])

In [114]:
tens_float = numbers/10
tens_float

array([8. , 4.6, 6.2, 5.8, 6.4, 7.7, 9.8, 2. , 3.5, 3.7])

In [115]:
tens_int = tens_float.astype(np.int8)
tens_int

array([8, 4, 6, 5, 6, 7, 9, 2, 3, 3], dtype=int8)

Another way of doing this, is first make thoes numbers into string, and then do some string stuff, get the number and pass through int process. in this process, we might find a value NaN, so we need to pass another parameter if the value is NaN it should put zero there. 

In [116]:
num_str = numbers.astype(str)
num_str

array(['80', '46', '62', '58', '64', '77', '98', '20', '35', '37'],
      dtype='<U21')

In [117]:
tens_digits = [int(s[-2]) if len(s) >= 2 else 0 for s in num_str]
tens_digits

[8, 4, 6, 5, 6, 7, 9, 2, 3, 3]

NOTE: always use second methods. 