### find the tens digit from a number of an array


In [49]:
import pandas as pd
import numpy as np

In [50]:
numbers = np.random.randint(0,100,10)
numbers

array([99,  4, 39, 98, 87, 26, 76, 23, 60, 90])

In [51]:
tens_float = numbers/10
tens_float

array([9.9, 0.4, 3.9, 9.8, 8.7, 2.6, 7.6, 2.3, 6. , 9. ])

In [52]:
tens_int = tens_float.astype(np.int8)
tens_int

array([9, 0, 3, 9, 8, 2, 7, 2, 6, 9], dtype=int8)